VS_LOAN.Core.Web/Controllers/PermissionGroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Mvc;
using VS_LOAN.Core.Repository;
using VS_LOAN.Core.Entity;
using VS_LOAN.Core.Entity.Model;
using VS_LOAN.Core.Utility;
using VS_LOAN.Core.Utility.Exceptions;
using VS_LOAN.Core.Web.Helpers;
using VS_LOAN.Core.Repository.Interfaces;

namespace VS_LOAN.Core.Web.Controllers
{
    public class PermissionGroupController : LoanController
    {
        protected readonly IGroupRepository _rpGroup;
        public PermissionGroupController(IGroupRepository groupRepository) : base()
        {
            _rpGroup = groupRepository;
        }
        public static Dictionary<string, ActionInfo> LstRole
        {
            get
            {
                Dictionary<string, ActionInfo> _lstRole = new Dictionary<string, ActionInfo>();
                _lstRole.Add("TaoMoi", new ActionInfo() { _formindex = IndexMenu.M_5_1, _href = "PermissionGroup/TaoMoi", _mangChucNang = new int[] { (int)QuyenIndex.QLNHomQuyen } });
                _lstRole.Add("DanhsachNhomQuyen", new ActionInfo() { _formindex = IndexMenu.M_5_2, _href = "PermissionGroup/DanhsachNhomQuyen", _mangChucNang = new int[] { (int)QuyenIndex.QLNHomQuyen } });
               
                return _lstRole;
            }
        }

        [CheckPermission(MangChucNang = new int[] { (int)QuyenIndex.QLNHomQuyen })]
        public ActionResult TaoMoi()
        {
            ViewBag.formindex = "";//LstRole[RouteData.Values["action"].ToString()]._formindex;
            return View();
        }
        
        
       


        [CheckPermission(MangChucNang = new int[] { (int)QuyenIndex.QLToNhom })]
        public ActionResult QLToNhom()
        {
            ViewBag.formindex = "";//LstRole[RouteData.Values["action"].ToString()]._formindex;
            return View();
        }

        

        [CheckPermission(MangChucNang = new int[] { (int)QuyenIndex.QLToNhom })]
        public ActionResult Sua()
        {
            ViewBag.formindex = LstRole["QLToNhom"]._formindex;
            if(Session["ToNhom_Sua_ID"] == null)
                return RedirectToAction("QLToNhom");
            int idNhom = (int)Session["ToNhom_Sua_ID"];
            ViewBag.ThongTinNhom = new GroupRepository().LayTheoMaAsync(idNhom);
            return View();
        }

        public ActionResult SuaToNhomByID(int id)
        {
            Session["ToNhom_Sua_ID"] = id;
            return RedirectToAction("Sua");
        }

      
       

        public ActionResult XemToNhomByID(int id)
        {
            Session["ToNhom_ChiTiet_ID"] = id;
            return RedirectToAction("ChiTiet");
        }

        [CheckPermission(MangChucNang = new int[] { (int)QuyenIndex.QLToNhom })]
        public ActionResult LuuSua(int maNhom, string ten, string tenNgan, int maNguoiQuanLy, int maNhomCha, List<int> lstThanhVien)
        {
            try
            {

                bool result = false;
                NhomModel nhom = new NhomModel();
                nhom.ID = maNhom;
                nhom.MaNguoiQL = maNguoiQuanLy;
                nhom.MaNhomCha = maNhomCha;
                if (maNhomCha != 0)
                    nhom.ChuoiMaCha = new GroupRepository().LayChuoiMaCha(maNhomCha) + "." + maNhomCha;
                else
                    nhom.ChuoiMaCha = "0";
                nhom.Ten = ten;
                nhom.TenNgan = tenNgan;
                result = new GroupRepository().Sua(nhom, lstThanhVien);
                if (result)
                {
                    return ToResponse(true,null, result);
                }
                return ToResponse(false,"Không thành công", 0);
            }
            catch (BusinessException ex)
            {
                return ToResponse(false, ex.Message);
            }
            
        }


        [CheckPermission(MangChucNang = new int[] { (int)QuyenIndex.CauHinhDuyet })]
        public ActionResult CauHinhDuyet()
        {
            ViewBag.formindex = "";//LstRole[RouteData.Values["action"].ToString()]._formindex;
            return View();
        }

       
    }
}

VS_LOAN.Core.Web/Controllers/ToNhomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Mvc;
using VS_LOAN.Core.Repository;
using VS_LOAN.Core.Entity;
using VS_LOAN.Core.Entity.Model;
using VS_LOAN.Core.Utility;
using VS_LOAN.Core.Utility.Exceptions;
using VS_LOAN.Core.Web.Helpers;
using VS_LOAN.Core.Repository.Interfaces;

namespace VS_LOAN.Core.Web.Controllers
{
    public class ToNhomController : LoanController
    {
        protected readonly IEmployeeRepository _rpEmployee;
        protected readonly IGroupRepository _rpGroup;
        public ToNhomController(IEmployeeRepository employeeRepository, IGroupRepository groupRepository) : base()
        {
            _rpEmployee = employeeRepository;
            _rpGroup = groupRepository;
        }
        public static Dictionary<string, ActionInfo> LstRole
        {
            get
            {
                Dictionary<string, ActionInfo> _lstRole = new Dictionary<string, ActionInfo>();
                _lstRole.Add("TaoMoi", new ActionInfo() { _formindex = IndexMenu.M_3_1, _href = "ToNhom/TaoMoi", _mangChucNang = new int[] { (int)QuyenIndex.QLToNhom } });
                _lstRole.Add("QLToNhom", new ActionInfo() { _formindex = IndexMenu.M_3_2, _href = "ToNhom/QLToNhom", _mangChucNang = new int[] { (int)QuyenIndex.QLToNhom } });
                _lstRole.Add("CauHinhDuyet", new ActionInfo() { _formindex = IndexMenu.M_3_3, _href = "ToNhom/CauHinhDuyet", _mangChucNang = new int[] { (int)QuyenIndex.QLToNhom } });
                return _lstRole;
            }
        }

        [CheckPermission(MangChucNang = new int[] { (int)QuyenIndex.QLToNhom })]
        public ActionResult TaoMoi()
        {
            ViewBag.formindex = LstRole[RouteData.Values["action"].ToString()]._formindex;
            return View();
        }


        public async Task<JsonResult> LayDSNhomCha(bool isAddAll = false)
        {
            List<NhomDropDownModel> rs = await _rpGroup.GetAll(GlobalData.User.IDUser);

            if (rs == null)
                rs = new List<NhomDropDownModel>();
            if (isAddAll)
            {
                rs.Add(new NhomDropDownModel { ID = 0, Ten = "Tất cả" });
            }
            return ToJsonResponse(true, null, rs);
        }

        [CheckPermission(MangChucNang = new int[] { (int)QuyenIndex.QLToNhom })]
        public ActionResult ThemMoi(string ten, string tenNgan, int maNguoiQuanLy, int maNhomCha, List<int> lstThanhVien)
        {

            try
            {

                int result = 0;
                NhomModel nhom = new NhomModel();
                nhom.MaNguoiQL = maNguoiQuanLy;
                nhom.MaNhomCha = maNhomCha;
                if (maNhomCha != 0)
                {
                    var parentCode = _rpGroup.LayChuoiMaCha(maNhomCha);
                    nhom.ChuoiMaCha = parentCode + "." + maNhomCha;
                }

                else
                    nhom.ChuoiMaCha = "0";
                nhom.Ten = ten;
                nhom.TenNgan = tenNgan;
                result = _rpGroup.Them(nhom, lstThanhVien, GlobalData.User.IDUser);
                if (result > 0)
                {
                    return ToResponse(true, null, result);

                }
                return ToResponse(false, "Không thành công", 0);
            }
            catch (BusinessException ex)
            {
                return ToResponse(false, ex.Message, 0);
            }

        }

        [CheckPermission(MangChucNang = new int[] { (int)QuyenIndex.QLToNhom })]
        public ActionResult QLToNhom()
        {
            ViewBag.formindex = LstRole[RouteData.Values["action"].ToString()]._formindex;
            return View();
        }
        public async Task<JsonResult> GetEmployeesByGroupId(int groupId, bool isLeader = false)
        {
            var results = await _rpEmployee.GetEmployeesByGroupId(groupId, isLeader);
            return ToJsonResponse(true, null, results);
        }
        [CheckPermission(MangChucNang = new int[] { (int)QuyenIndex.QLToNhom })]
        public async Task<JsonResult> LayDSToNhomCon(int maNhomCha)
        {

            RMessage message = new RMessage { code = Resources.Global.Message_Succ, success = true };
            List<ThongTinToNhomModel> rs = new List<ThongTinToNhomModel>();
            try
            {
                rs = await _rpGroup.LayDSNhomConAsync(maNhomCha, GlobalData.User.IDUser);
                if (rs == null)
                    rs = new List<ThongTinToNhomModel>();
            }
            catch (BusinessException ex)
            {
                message.success = false;
                message.code = ex.Message;
            }
            return Json(rs, JsonRequestBehavior.AllowGet);
        }

        [CheckPermission(MangChucNang = new int[] { (int)QuyenIndex.QLToNhom })]
        public async Task<ActionResult> Sua(int id)
        {

            ViewBag.model = await _rpGroup.LayTheoMaAsync(id);
            return View();
        }

        public async Task<JsonResult> GetMember(int groupId)
        {
            var result = await _rpGroup.LayDSThanhVienNhomAsync(groupId, GlobalData.User.IDUser);
            return ToJsonResponse(true, null, result);
        }
      

        [CheckPermission(MangChucNang = new int[] { (int)QuyenIndex.QLToNhom })]
        public async Task<ActionResult> ChiTiet(int id)
        {
            ViewBag.formindex = LstRole["QLToNhom"]._formindex;

            ViewBag.model = await _rpGroup.LayChiTietTheoMaAsync(id);
            return View();
        }


        [CheckPermission(MangChucNang = new int[] { (int)QuyenIndex.QLToNhom })]
        public ActionResult LuuSua(int maNhom, string ten, string tenNgan, int maNguoiQuanLy, int maNhomCha, List<int> lstThanhVien)
        {
            try
            {

                bool result = false;
                NhomModel nhom = new NhomModel();
                nhom.ID = maNhom;
                nhom.MaNguoiQL = maNguoiQuanLy;
                nhom.MaNhomCha = maNhomCha;
                if (maNhomCha != 0)
                {
                    var parentCode = _rpGroup.LayChuoiMaCha(maNhomCha);
                    nhom.ChuoiMaCha = parentCode + "." + maNhomCha;
                }

                else
                    nhom.ChuoiMaCha = "0";
                nhom.Ten = ten;
                nhom.TenNgan = tenNgan;
                result = _rpGroup.Sua(nhom, lstThanhVien);
                if (result)
                {
                    return ToResponse(true, null, result);
                }
                return ToResponse(false);
            }
            catch (BusinessException ex)
            {
                return ToResponse(false, ex.Message, null);
            }

        }

        public JsonResult LayDSChiTietThanhVien(int maNhom)
        {

            RMessage message = new RMessage { code = Resources.Global.Message_Error, success = false };
            List<ThongTinNhanVienModel> rs = new List<ThongTinNhanVienModel>();
            try
            {
                rs = _rpGroup.LayDSChiTietThanhVienNhom(maNhom);
                if (rs == null)
                    rs = new List<ThongTinNhanVienModel>();
            }
            catch (BusinessException ex)
            {
                message.success = false;
                message.code = ex.Message;
            }
            return Json(rs, JsonRequestBehavior.AllowGet);
        }

        [CheckPermission(MangChucNang = new int[] { (int)QuyenIndex.CauHinhDuyet })]
        public ActionResult CauHinhDuyet()
        {
            ViewBag.formindex = LstRole[RouteData.Values["action"].ToString()]._formindex;
            return View();
        }

        [CheckPermission(MangChucNang = new int[] { (int)QuyenIndex.QLToNhom })]
        public ActionResult LuuCauHinh(int maNhanVien, List<int> lstIDNhom)
        {

            try
            {
                bool result = _rpEmployee.CapNhat(maNhanVien, lstIDNhom);
                return ToResponse(result);
            }
            catch (BusinessException ex)
            {
                return ToResponse(false, null, ex.Message);
            }
        }


        [CheckPermission(MangChucNang = new int[] { (int)QuyenIndex.QLToNhom })]
        public async Task<ActionResult> Xoa(int id)
        {
            if (id <= 0)
            {
                return ToJsonResponse(false, "Dữ liệu không hợp lệ");
            }
            var isAdmin = GlobalData.User.UserType == (int)UserTypeEnum.Admin ? true : false;
            if (!isAdmin)
            {
                return ToJsonResponse(false, "Bạn không đủ quyền để xóa nhân viên");
            }
            var result = await _rpGroup.Delete(id);
            return ToJsonResponse(result);
        }
    }
}

VS_LOAN.Core.Web/Views/PermissionGroup/TaoMoi.cshtml
@using VS_LOAN.Core.Web.Resources;
@{
    ViewBag.Title = "Tạo nhóm quyền";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model String









<script type="text/javascript">
    SetActiveMenu('@ViewBag.formindex', 2);
</script>
<div class="main-content-inner">
    <div class="breadcrumbs" id="breadcrumbs">
        <ul class="breadcrumb">
            <li>
                <i class="fa fa-caret-right"></i>
                <a href="#">Tạo nhóm quyền</a>
            </li>
        </ul>
    </div>
    <div class="page-content" id="panel_body">
        <div class="row">
            <div class="col-xs-12">
                <h3 class="header smaller lighter blue">1.Thông tin nhóm quyền:</h3>
                <form class="form-horizontal" role="form">
                    <div class="form-group">
                        <label for="form-field-1" class="col-sm-2 control-label no-padding-right">Tên <span class="required">(*)</span> </label>
                        <div class="col-sm-4">
                            <input type="text" id="txtTenNhom" placeholder="Nhập tên nhóm" class="form-control">
                        </div>
                        <label for="form-field-1" class="col-sm-2 control-label no-padding-right">Tên ngắn <span class="required">(*)</span> </label>
                        <div class="col-sm-4">
                            <input type="text" id="txtTenNgan" placeholder="Nhập tên ngắn" class="form-control">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label no-padding-right">
                            <input name="radio-admin" type="radio" checked="checked" value="1" class="ace">
                            <span class="lbl"> Ngày tạo</span>
                        </label>
                        <label class="control-label no-padding-right">
                            <input name="radio-ngay" type="radio" checked="checked" value="1" class="ace">
                            <span class="lbl"> Ngày tạo</span>
                        </label>
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <h3 class="header smaller lighter blue">2.Thành viên nhóm:</h3>
                <div class="form-group">
                    <div class="col-sm-12">
                        <select multiple="multiple" size="10" name="duallistbox_demo1[]" id="duallistNhanVien"></select>
                        <div class="hr hr-16 hr-dotted"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <hr />
                <div class="pull-right">
                    <a class="btn btn-sm btn-primary" id="btn_Save">
                        Lưu
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Content/ace-master/assets/js/jquery.bootstrap-duallistbox.min.js"></script>
<script>
    $(document).ready(function () {
        LayNhanVien();
        LayDSNhanVienQL();
        LayDSNhom();
    });
</script>
<script>
    jQuery(function ($) {
        var demo1 = $('select[name="duallistbox_demo1[]"]').bootstrapDualListbox({ infoTextFiltered: '<span class="label label-purple label-lg">Filtered</span>', filterPlaceHolder: '', filterTextClear: '', infoText: '', infoTextFiltered: '' });

        var container1 = demo1.bootstrapDualListbox('getContainer');
        container1.find('.btn').addClass('btn-white btn-info btn-bold');

        ///////////////////
        //example taken from plugin's page at: https://twitter.github.io/typeahead.js/examples/
        var substringMatcher = function (strs) {
            return function findMatches(q, cb) {
                var matches, substringRegex;

                // an array that will be populated with substring matches
                matches = [];

                // regex used to determine if a string contains the substring `q`
                substrRegex = new RegExp(q, 'i');

                // iterate through the pool of strings and for any string that
                // contains the substring `q`, add it to the `matches` array
                $.each(strs, function (i, str) {
                    if (substrRegex.test(str)) {
                        // the typeahead jQuery plugin expects suggestions to a
                        // JavaScript object, refer to typeahead docs for more info
                        matches.push({ value: str });
                    }
                });

                cb(matches);
            }
        }

        //in ajax mode, remove remaining elements before leaving page
        $(document).one('ajaxloadstart.page', function (e) {
            $('select[name="duallistbox_demo1[]"]').bootstrapDualListbox('destroy');
        });

    });
</script>
<script>
    function LayNhanVien() {
        $('#duallistNhanVien').empty();
        $.ajax({
            type: "POST",
            url: '@Url.Action("GetAllEmployee", "Employee")',
            data: { },
            success: function (data) {
                if (data != null) {
                    if (data.DSNhanVien != null && data.DSNhanVien.length > 0) {
                        $.each(data.DSNhanVien, function (index, item) {
                            $('#duallistNhanVien').append("<option value='" + item.IDUser + "'>" + item.FullName + "</option>");
                        });
                    }
                }
                $('#duallistNhanVien').bootstrapDualListbox('refresh', true);
            },
            complete: function () {
            },
            error: function (jqXHR, exception) {
                showError(jqXHR, exception);
            }
        });
    }

    function LayDSNhanVienQL()
    {
        $('#ddlNguoiQL').empty();
        $('#ddlNguoiQL').append("<option value='0'></option>");
        $.ajax({
            type: "POST",
            url: '@Url.Action("GetAllEmployee", "Employee")',
            data: {},
            success: function (data) {
                if (data != null) {
                    if (data.DSNhanVien != null && data.DSNhanVien.length > 0) {
                        $.each(data.DSNhanVien, function (index, item) {
                            $('#ddlNguoiQL').append("<option value='" + item.IDUser + "'>" + item.FullName + "</option>");
                        });
                        if (data.DSNhanVien.length == 1) {
                            $('#ddlNguoiQL').val(data.DSNhanVien[0].IDUser);
                        }
                    }
                }
                $('#ddlNguoiQL').chosen().trigger("chosen:updated");
                $('#ddlNguoiQL').trigger("change");
            },
            complete: function () {
            },
            error: function (jqXHR, exception) {
                showError(jqXHR, exception);
            }
        });
    }

    function LayDSNhom() {
        $('#ddlNhomCha').empty();
        $('#ddlNhomCha').append("<option value='0'></option>");
        $.ajax({
            type: "POST",
            url: '@Url.Action("LayDSNhomCha", "ToNhom")',
            data: {},
            success: function (data) {
                if (data != null) {
                    if (data.DSNhom != null && data.DSNhom.length > 0) {
                        $.each(data.DSNhom, function (index, item) {
                            $('#ddlNhomCha').append("<option value='" + item.ID + "'>" + item.Ten + "</option>");
                        });
                        if (data.DSNhom.length == 1) {
                            $('#ddlNhomCha').val(data.DSNhom[0].IDUser);
                        }
                    }
                }
                $('#ddlNhomCha').chosen().trigger("chosen:updated");
                $('#ddlNhomCha').trigger("change");
            },
            complete: function () {
            },
            error: function (jqXHR, exception) {
                showError(jqXHR, exception);
            }
        });
    }
</script>
<script>
    $('#btn_Save').click(function (e) {
        if ($('#txtTenNhom').val() == '') {
            swal({
                title: "",
                text: "Vui lòng nhập tên nhóm!",
                type: "error",
                timer: 4000,
                showConfirmButton: true,
            });
            return;
        }
        if ($('#txtTenNgan').val() == '') {
            swal({
                title: "",
                text: "Vui lòng nhập tên ngắn!",
                type: "error",
                timer: 4000,
                showConfirmButton: true,
            });
            return;
        }
        var lstRightSelect = $('select[name="duallistbox_demo1[]_helper2"]')[0];
        var lstSelectedId = [];
        for (var i = 0; i < lstRightSelect.length; i++) {
            lstSelectedId.push(lstRightSelect[i].attributes[0].value);
        }
        if (lstSelectedId.length == 0)
        {
            swal({
                title: "",
                text: "Vui lòng chọn thành viên nhóm!",
                type: "error",
                timer: 4000,
                showConfirmButton: true,
            });
            return;
        }
        var objectSend = JSON.stringify({ 'ten': $('#txtTenNhom').val(), 'tenNgan': $('#txtTenNgan').val(), 'maNguoiQuanLy': $('#ddlNguoiQL').val(), 'maNhomCha': $('#ddlNhomCha').val(), 'lstThanhVien': lstSelectedId });
        $.ajax({
            traditional: true,
            url: '@Url.Action("ThemMoi", "ToNhom")',
            type: "POST",
            contentType: "application/json; charset=utf-8",
            data: objectSend,
            success: function (data) {
                if (data.Message.Result == true) {
                    swal({
                        title: "@Html.Raw(Global.Message_Title)",
                        text: data.Message.ErrorMessage,
                        type: "success",
                        timer: 4000,
                        showConfirmButton: true,
                    }, function () {
                        window.location = window.location;
                    });
                }
                else {
                    swal({
                        title: "@Html.Raw(Global.Message_Title)",
                        text: data.Message.ErrorMessage,
                        type: "error",
                        timer: 4000,
                        showConfirmButton: true,
                    });
                }
            },
            error: function (jqXHR, exception) {
                showError(jqXHR, exception);
            },
            complete: function () {
                $('#panel_body').unblock();
            },
        });
    });
</script>