VS_LOAN.Core.Web/Controllers/SanPhamVayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;
using VS_LOAN.Core.Repository;
using VS_LOAN.Core.Entity;
using VS_LOAN.Core.Entity.Model;
using VS_LOAN.Core.Utility;
using VS_LOAN.Core.Utility.Exceptions;
using VS_LOAN.Core.Web.Helpers;
using VS_LOAN.Core.Web.Helpers.DataTables;

namespace VS_LOAN.Core.Web.Controllers
{
    public class SanPhamVayController : LoanController
    {
        public static Dictionary<string, ActionInfo> LstRole
        {
            get
            {
                Dictionary<string, ActionInfo> _lstRole = new Dictionary<string, ActionInfo>();
                _lstRole.Add("QuanLySanPham", new ActionInfo() { _formindex = IndexMenu.M_4_1, _href = "SanPhamVay/QuanLySanPham", _mangChucNang = new int[] { (int)QuyenIndex.QLSanPhamVay } });
                _lstRole.Add("Import", new ActionInfo() { _formindex = IndexMenu.M_4_2, _href = "SanPhamVay/Import", _mangChucNang = new int[] { (int)QuyenIndex.QLSanPhamVay } });
                return _lstRole;
            }
        }

        [CheckPermission(MangChucNang = new int[] { (int)QuyenIndex.QLSanPhamVay })]
        public ActionResult QuanLySanPham()
        {
            ViewBag.formindex = "";//LstRole[RouteData.Values["action"].ToString()]._formindex;
            return View();
        }

        [CheckPermission(MangChucNang = new int[] { (int)QuyenIndex.Public })]
        public JsonResult LayDS(string ngay)
        {

            RMessage message = new RMessage { code = Resources.Global.Message_Error, success = false };
            List<ThongTinSanPhamVayModel> rs = new List<ThongTinSanPhamVayModel>();
            try
            {
                DateTime dtDate = DateTime.MinValue;
                if (ngay != "")
                    dtDate = DateTimeFormat.ConvertddMMyyyyToDateTime(ngay);
                rs = new SanPhamBLL().LayThongTinSanPhamByID(3, dtDate);
                if (rs == null)
                    rs = new List<ThongTinSanPhamVayModel>();
            }
            catch (BusinessException ex)
            {
                message.success = false;
                message.code = ex.Message;
            }
            return Json(rs, JsonRequestBehavior.AllowGet);
        }

        [CheckPermission(MangChucNang = new int[] { (int)QuyenIndex.QLToNhom })]
        public ActionResult ThemMoi(string ma, string ngay)
        {
            
            try
            {
                if (new SanPhamBLL().Trung(ma) == true)
                {
                    return ToResponse(false, "Mã sản phẩm bị trùng!", 0);
                    
                }
                else
                {
                    DateTime dtDate = DateTime.MinValue;
                    try
                    {
                        if (ngay != "")
                            dtDate = DateTimeFormat.ConvertddMMyyyyToDateTime(ngay);
                    }
                    catch (Exception)
                    {
                        return ToResponse(false, "Ngày không đúng định dạng!", 0);
                        
                    }

                    int result = 0;
                    SanPhamVayModel sp = new SanPhamVayModel();
                    sp.Ma = ma;
                    sp.Ten = ma;
                    sp.MaNguoiTao = GlobalData.User.IDUser;
                    sp.NgayTao = dtDate;
                    sp.MaDoiTac = 3;
                    sp.Loai = 1;
                    result = new SanPhamBLL().Them(sp);
                    if (result > 0)
                    {
                        return ToResponse(true, Resources.Global.Message_Succ, result);
                    }
                    return ToResponse(false,"Không thành công", 0);
                }
            }
            catch (BusinessException ex)
            {
                return ToResponse(false, ex.Message);
            }
           
        }

        [CheckPermission(MangChucNang = new int[] { (int)QuyenIndex.QLSanPhamVay })]
        public ActionResult Xoa(int id)
        {
            
            try
            {

                bool result = false;
                result = new SanPhamBLL().Xoa(id);
                
                return ToResponse(result);
            }
            catch (BusinessException ex)
            {
                return ToResponse(false, ex.Message);
            }
            
        }

        [CheckPermission(MangChucNang = new int[] { (int)QuyenIndex.QLSanPhamVay })]
        public ActionResult Import()
        {
            ViewBag.formindex = "";//LstRole[RouteData.Values["action"].ToString()]._formindex;
            return View();
        }
        public ActionResult AjaxHandler(jQueryDataTableParamModel param, List<SanPhamModel> lstSanPham)
        {
            if (lstSanPham == null)
                lstSanPham = new List<SanPhamModel>();
            var displayedCompanies = lstSanPham
                               .Skip(param.iDisplayStart)
                               .Take(param.iDisplayLength);
            return Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = lstSanPham.Count(),
                iTotalDisplayRecords = lstSanPham.Count(),
                aaData = displayedCompanies
            },
                                JsonRequestBehavior.AllowGet);
        }
        [CheckPermission(MangChucNang = new int[] { (int)QuyenIndex.QLSanPhamVay })]
        public ActionResult LuuImportSPV(List<SanPhamModel> lstSanPham, string ngay)
        {
           
            try
            {
                bool result = true;
                if(lstSanPham!=null)
                {
                    foreach(var item in lstSanPham)
                    {
                        if (new SanPhamBLL().Trung(item.Ten) == true)
                        {
                            item.TrangThai = 2;// Trùng
                        }
                        else
                        {
                            DateTime dtDate = DateTime.MinValue;
                            try
                            {
                                if (ngay != "")
                                    dtDate = DateTimeFormat.ConvertddMMyyyyToDateTime(ngay);
                            }
                            catch (Exception)
                            {
                                return ToResponse(false, null, "Ngày không đúng định dạng!");
                                
                            }
                            SanPhamVayModel sp = new SanPhamVayModel();
                            sp.Ma = item.Ten;
                            sp.Ten = item.Ten;
                            sp.MaNguoiTao = GlobalData.User.IDUser;
                            sp.NgayTao = dtDate;
                            sp.MaDoiTac = 3;
                            sp.Loai = 1;
                           
                            if (new SanPhamBLL().Them(sp) > 0)
                            {
                                item.TrangThai = 1;
                            }
                            else
                            {
                                item.TrangThai = 3;
                            }
                        }

                    }
                    if (result)
                    {
                        return ToResponse(true,null, lstSanPham);
                    }
                    return ToResponse(false);
                }
                return ToResponse(false);
            }
            catch (BusinessException ex)
            {
                return ToResponse(false, ex.Message);
            }
            
        }
        public FileResult DownloadFile(string file)
        {
            byte[] fileBytes = System.IO.File.ReadAllBytes(AppDomain.CurrentDomain.BaseDirectory + "App_Data\\ImportSanPham\\" + file);
            var response = new FileContentResult(fileBytes, "application/octet-stream");
            response.FileDownloadName = file;
            return response;
        }
    }
}

VS_LOAN.Core.Web/Views/SanPhamVay/QuanLySanPham.cshtml
@using VS_LOAN.Core.Web.Resources;
@{
    ViewBag.Title = "Quản lý mã APP";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model String









<script type="text/javascript">
    SetActiveMenu('@ViewBag.formindex', 2);
</script>
<div class="main-content-inner">
    <div class="breadcrumbs" id="breadcrumbs">
        <ul class="breadcrumb">
            <li>
                <i class="fa fa-caret-right"></i>
                <a href="#">Quản lý mã APP</a>
            </li>
        </ul>
    </div>
    <div class="page-content" id="panel_body">
        <div class="row">
            <div class="col-xs-12">
                <form class="form-horizontal" role="form">
                    <div class="form-group">
                        <label for="form-field-1" class="col-sm-2 control-label no-padding-right">Ngày <span class="required">(*)</span> </label>
                        <div class="col-sm-2 col-xs-12">
                            <div class="input-group">
                                <input class="form-control date-picker" id="txtCreateDate" />
                                <span class="input-group-addon">
                                    <i class="fa fa-calendar bigger-110"></i>
                                </span>
                            </div>
                        </div>
                        <label for="form-field-1" class="col-sm-2 control-label no-padding-right">Mã APP <span class="required">(*)</span> </label>
                        <div class="col-sm-4">
                            <input type="text" id="txtMa" placeholder="Nhập mã app" class="form-control">
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <hr />
                <div class="pull-right">
                    <a class="btn btn-sm btn-primary" id="btn_Save">
                        <i class="ace-icon glyphicon glyphicon-plus"></i>
                        Thêm
                    </a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="clearfix">
                    <div class="pull-right tableTools-container"></div>
                </div>
                <div class="table-header">
                    Danh sách mã APP
                </div>
                <!-- div.table-responsive -->
                <!-- div.dataTables_borderWrap -->
                <div>
                    <table id="dtSource" class="table table-striped table-bordered table-hover" width="100%">
                        <thead>
                            <tr>
                                <th style="width: 50px" class="center">STT</th>
                                <th style="width: 250px">Mã</th>
                                <th>Người tạo</th>
                                <th style="width: 100px">Thao tác</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
            <!-- /.col -->
        </div>
    </div>
</div>
<script>
    var strLoading = '@Global.Message_Loading';
    $(document).ready(function e() {
        $('#txtCreateDate').datepicker({
            dateFormat: 'dd-mm-yy',
            onSelect: function (datesel) {
                $('#txtCreateDate').trigger('change');
            }
        }).next().on(ace.click_event, function () {
            $(this).prev().focus();
        });
        $("#txtCreateDate").datepicker({ dateFormat: 'yy/mm/dd' }).datepicker("setDate", new Date().getDay + 0);

        InitTable();
    });
</script>
<script>
    function InitTable() {
        showBlock($('#panel_body'), strLoading);
        var table = $('#dtSource').DataTable({
            ajax: {
                url: '@Url.Action("LayDS", "SanPhamVay")'
                    , dataSrc: '',
                type: "GET",
                contentType: "application/json",
                data: function (d) {
                    d.ngay = $('#txtCreateDate').val();
                },
                error: function (jqXHR, exception) {
                    showError(jqXHR, exception);
                },
                complete: function () {
                    $('#panel_body').unblock();
                }
            },
            columns: [
                {
                    data: null,
                    bSortable: false,
                    searchable: false
                   , orderable: false
                   , targets: 0
                   , className: "ColumnCenterClassName",
                    sClass: 'text-center'
                }
                ,
               {// Company Name
                   data: null,
                   bSortable: false,
                   "render": function (data, type, full, meta) {
                       return data.Ma;
                   },
                   className: 'text-left'
               }
               ,
               {// Company Name
                   data: null,
                   bSortable: false,
                   "render": function (data, type, full, meta) {
                       return data.NguoiTao;
                   },
                   className: 'text-left'
               }
                , {// Thao tác
                    data: null,
                    bSortable: false,
                    "render": function (data, type, full, meta) {
                        var thaoTac = "";
                        thaoTac += "<div class='action-buttons'>";
                        thaoTac += "<a title='@Global.Button_Delete' class=\"red\" style='cursor: pointer' id='" + data.ID + "' onClick='Xoa(this)'>";
                        thaoTac += "<i class=\"ace-icon fa fa-trash bigger-130\">";
                        thaoTac += "</i>";
                        thaoTac += "</a>";
                        thaoTac += "</div>";
                        return thaoTac;
                    }
                    , sClass: 'text-center'
                }

            ],
            "aaSorting": []
            //, order: [0, 'asc']
                , language: {
                    lengthMenu: '@Html.Raw(Global.Table_LengthMenu)'
                    , info: '@Html.Raw(Global.Table_Info)'
                    , infoEmpty: '@Html.Raw(Global.Table_InfoEmpty)'
                    , zeroRecords: "@Html.Raw(Global.Table_ZeroRecords)"
                    , search: '@Html.Raw(Global.Table_Search)'
                    , decimal: ","
                    , thousands: "."
                    , paginate: {
                        first: "@Html.Raw(Global.Table_Paginate_First)",
                        last: "@Html.Raw(Global.Table_Paginate_Last)",
                        next: "@Html.Raw(Global.Table_Paginate_Next)",
                        previous: '@Html.Raw(Global.Table_Paginate_Previous)'
                    }
                },
            "fnInitComplete": function () {
                $("#dtSource").css("width", "100%");
                $('#dtSource').DataTable().columns.adjust().draw();
            }
        });

        //Thứ tự bảng dữ liệu
        table.on('order.dt search.dt', function () {
            table.column(0, { search: 'applied', order: 'applied' }).nodes().each(function (cell, i) {
                cell.innerHTML = i + 1;
            });
        }).draw();

        //$('#dtSource tbody').on('click', 'tr', function () {
        //    var data = table.row(this).data();
        //    alert('You clicked on ' + data.ID);
        //});
    }
</script>
<script>
    $('#txtCreateDate').change(function() {
        showBlock($('#panel_body'), strLoading);
        $('#dtSource').DataTable().ajax.reload();
        $('#dtSource').DataTable().columns.adjust().draw();
    });
</script>
<script>
    $('#btn_Save').click(function (e) {
        if ($('#txtCreateDate').val() == '') {
            swal({
                title: "",
                text: "Vui lòng chọn ngày!",
                type: "error",
                timer: 4000,
                showConfirmButton: true,
            });
            return;
        }
        if ($('#txtMa').val() == '') {
            swal({
                title: "",
                text: "Vui lòng nhập mã sản phẩm!",
                type: "error",
                timer: 4000,
                showConfirmButton: true,
            });
            return;
        }
        showBlock($('#panel_body'), strLoading);
        var objectSend = JSON.stringify({ 'ma': $('#txtMa').val(), 'ngay': $('#txtCreateDate').val() });
        $.ajax({
            traditional: true,
            url: '@Url.Action("ThemMoi", "SanPhamVay")',
            type: "POST",
            contentType: "application/json; charset=utf-8",
            data: objectSend,
            success: function (data) {
                if (data.success == true) {
                    swal({
                        title: "@Html.Raw(Global.Message_Title)",
                        text: "Thành công",
                        type: "success",
                        timer: 4000,
                        showConfirmButton: true,
                    }, function () {
                        showBlock($('#panel_body'), strLoading);
                        $('#dtSource').DataTable().ajax.reload();
                        $('#dtSource').DataTable().columns.adjust().draw();
                    });
                }
                else {
                    swal({
                        title: "@Html.Raw(Global.Message_Title)",
                        text: data.code,
                        type: "error",
                        timer: 4000,
                        showConfirmButton: true,
                    });
                }
            },
            error: function (jqXHR, exception) {
                showError(jqXHR, exception);
            },
            complete: function () {
                $('#panel_body').unblock();
            },
        });
    });
</script>
<script>
    function Xoa(e) {
        var element = $(e);
        swal({
            title: "@Html.Raw(Global.DialogConfirmYesNo)",
            text: "",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "@Html.Raw(Global.DialogConfirmYes)",
            cancelButtonText: "@Html.Raw(Global.DialogConfirmNo)",
            closeOnConfirm: false
        }, function () {
            var id = element.attr("id");
            showBlock($('#panel_body'), strLoading);
            var objectSend = JSON.stringify({ 'id': id });
            $.ajax({
                url: '/SanPhamVay/Xoa',
                type: "POST",
                contentType: "application/json; charset=utf-8",
                processData: false,
                data: objectSend,
                success: function (data) {
                    if (data.success == true) {
                        swal({
                            title: "",
                            text: "Xóa thành công",
                            type: "success",
                            timer: 4000,
                            showConfirmButton: true,
                        });
                    }
                    else {
                        swal({
                            title: "",
                            text: data.code,
                            type: "error",
                            timer: 4000,
                            showConfirmButton: true,
                        });
                        return;
                    }
                },
                error: function (jqXHR, exception) {
                    showError(jqXHR, exception);
                },
                complete: function () {
                    $('#dtSource').DataTable().ajax.reload();
                    $('#dtSource').DataTable().columns.adjust().draw();
                    $('#panel_body').unblock();
                },
            });
        }
        );
    }
</script>